library(dtplyr)
library(tidyverse)
mecha_data <- read.csv("MechaCar_mpg.csv",stringsAsFactors = F,check.names = F)
lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD, data=mecha_data) 
summary(lm(mpg ~ vehicle_length+vehicle_weight+spoiler_angle+ground_clearance+AWD, data=mecha_data))
Suspension_table<-read.csv(file = "Suspension_Coil.csv",check.names = F, stringsAsFactors = F)
total_summary<-Suspension_table %>% summarize(Mean=mean(PSI),Median = median(PSI),Variance = var(PSI),SD = sd(PSI))
lot_summary<-Suspension_table %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI),Median = median(PSI),Variance = var(PSI),SD = sd(PSI))
t.test(Suspension_table$PSI,mu=1500)
t.test(subset(Suspension_table,Manufacturing_Lot=="Lot1")$PSI,mu=1500)
t.test(subset(Suspension_table,Manufacturing_Lot=="Lot2")$PSI,mu=1500)
t.test(subset(Suspension_table,Manufacturing_Lot=="Lot3")$PSI,mu=1500)